import { app } from 'electron';
import { type SQLJsDatabase as DrizzleDatabase, drizzle } from 'drizzle-orm/sql-js';
import { migrate } from 'drizzle-orm/sql-js/migrator';
import * as fs from 'fs';
import * as path from 'path';
import logger from '@/lib/utils/logger';
import * as schema from './schema';

// Dynamic require for sql.js to avoid bundling issues
// eslint-disable-next-line @typescript-eslint/no-require-imports
const initSqlJs = require('sql.js') as typeof import('sql.js').default;
type SqlJsDatabase = import('sql.js').Database;

let db: DrizzleDatabase<typeof schema> | null = null;
let sqlite: SqlJsDatabase | null = null;
let dbPath: string = '';
let migrationsFolder: string = '';

export function getDbPath(): string {
  return path.join(app.getPath('userData'), 'xplane-data.db');
}

/**
 * Read the current schema fingerprint from Drizzle's snapshot.
 * This ID is generated by `drizzle-kit generate` and changes whenever the schema changes.
 */
function getSchemaFingerprint(): string {
  const snapshotDir = path.join(migrationsFolder, 'meta');
  const files = fs
    .readdirSync(snapshotDir)
    .filter((f) => f.endsWith('_snapshot.json'))
    .sort();
  if (files.length === 0) throw new Error('No migration snapshots found in ' + snapshotDir);
  const latestFile = files[files.length - 1]!;
  const snapshot = JSON.parse(fs.readFileSync(path.join(snapshotDir, latestFile), 'utf-8'));
  if (!snapshot.id) throw new Error('Migration snapshot missing id field');
  return snapshot.id;
}

/**
 * Clean up leftover .old-* database files from previous failed deletions (Windows file lock workaround).
 */
function cleanupOldDbFiles(): void {
  try {
    const dir = path.dirname(dbPath);
    const base = path.basename(dbPath);
    for (const file of fs.readdirSync(dir)) {
      if (file.startsWith(base + '.old-')) {
        try {
          fs.unlinkSync(path.join(dir, file));
        } catch {
          /* still locked, will retry next launch */
        }
      }
    }
  } catch {
    /* non-critical */
  }
}

/**
 * Delete the database if its schema doesn't match the current Drizzle snapshot.
 * The DB is purely a cache of X-Plane files — all data is rescanned automatically.
 */
function deleteStaleDb(fingerprint: string): void {
  if (!fs.existsSync(dbPath)) return;

  const versionPath = dbPath + '.version';
  let stored: string;

  try {
    stored = fs.existsSync(versionPath) ? fs.readFileSync(versionPath, 'utf-8').trim() : '';
  } catch {
    stored = '';
  }

  if (stored !== fingerprint) {
    logger.data.info(`Schema changed — deleting stale database`);
    try {
      fs.unlinkSync(dbPath);
    } catch {
      // Windows: file may be locked by antivirus/indexer — rename as fallback
      fs.renameSync(dbPath, `${dbPath}.old-${Date.now()}`);
    }
    try {
      fs.unlinkSync(versionPath);
    } catch {
      /* already gone */
    }
  }
}

/**
 * Drops the in-memory database without writing it back, deletes the cache files
 * and relaunches; the next launch rebuilds everything from X-Plane's files.
 */
function discardDbAndRelaunch(): void {
  sqlite = null;
  db = null;
  if (saveTimer) clearTimeout(saveTimer);
  saveTimer = null;
  try {
    if (fs.existsSync(dbPath)) fs.unlinkSync(dbPath);
  } catch {
    try {
      fs.renameSync(dbPath, `${dbPath}.old-${Date.now()}`);
    } catch {
      /* give up on cleanup */
    }
  }
  try {
    if (fs.existsSync(dbPath + '.version')) fs.unlinkSync(dbPath + '.version');
  } catch {
    /* non-critical */
  }
  app.relaunch();
  app.exit(0);
}

const CORRUPTION_PATTERN =
  /database disk image is malformed|file is not a database|SQLITE_CORRUPT/i;

/**
 * Recovers from a corrupt cache found after startup: a file with an intact
 * header opens and migrates, then every launch fails on its first query
 * (Sentry X-DISPATCH-3E). Returns false, doing nothing, for any other error.
 */
export function recoverFromCorruption(err: unknown): boolean {
  const message = err instanceof Error ? err.message : String(err);
  if (!dbPath || !CORRUPTION_PATTERN.test(message)) return false;
  logger.data.warn(`Database is corrupt, deleting and restarting: ${message}`);
  discardDbAndRelaunch();
  return true;
}

export async function initDb(): Promise<DrizzleDatabase<typeof schema>> {
  if (db) return db;

  dbPath = getDbPath();
  migrationsFolder = path.join(app.getAppPath(), 'drizzle');

  logger.data.info(`Database initializing: ${dbPath}`);

  cleanupOldDbFiles();

  const fingerprint = getSchemaFingerprint();
  deleteStaleDb(fingerprint);

  const SQL = await initSqlJs();

  // Try opening existing DB, fall back to fresh DB on any error.
  // The DB is a cache — safe to delete and rebuild from X-Plane files.
  let data: Buffer | undefined;
  if (fs.existsSync(dbPath)) {
    data = await fs.promises.readFile(dbPath);
  }

  try {
    sqlite = new SQL.Database(data);
    db = drizzle(sqlite, { schema });
    migrate(db, { migrationsFolder });
  } catch (err) {
    logger.data.warn(`Database open/migrate failed, deleting and restarting: ${err}`);
    discardDbAndRelaunch();
    throw err; // unreachable, but satisfies return type
  }

  fs.writeFileSync(dbPath + '.version', fingerprint);

  logger.data.info(`Database initialized: ${dbPath}`);
  return db;
}

export function getDb(): DrizzleDatabase<typeof schema> {
  if (!db) {
    throw new Error('Database not initialized. Call initDb() first.');
  }
  return db;
}

/** True once initDb() has assigned the singleton. Use this to gate read-only
 * callers that fire before app startup completes (e.g. the renderer asking
 * for a status snapshot while initDb is still running). */
export function isDbReady(): boolean {
  return db !== null;
}

/** Raw sql.js handle for debug queries — only use in dev tools */
export function getSqlite(): SqlJsDatabase | null {
  return sqlite;
}

// Saves are debounced: several loaders finishing over a load session
// (navaids, waypoints, airways, airspaces, airports) used to each serialize
// and write the entire database, which runs to hundreds of MB. Each save
// request pushes the timer back, so one write lands after the last loader —
// the window must outlast the gaps between them. The DB is a rebuildable
// cache, so deferring the write costs nothing on a crash, and quit flushes
// synchronously regardless.
const SAVE_COALESCE_MS = 5000;
let saveTimer: NodeJS.Timeout | null = null;
let saveInFlight = false;
let saveQueued = false;

function exportDbBuffer(): Buffer | null {
  if (!sqlite || !dbPath) return null;
  return Buffer.from(sqlite.export());
}

async function writeDbToDisk(): Promise<void> {
  if (saveInFlight) {
    saveQueued = true;
    return;
  }
  saveInFlight = true;
  try {
    const buffer = exportDbBuffer();
    if (!buffer) return;
    const dir = path.dirname(dbPath);
    await fs.promises.mkdir(dir, { recursive: true });
    // Write to a sibling temp file and rename so a crash mid-write never
    // leaves a truncated database behind.
    const tmpPath = `${dbPath}.tmp`;
    await fs.promises.writeFile(tmpPath, buffer);
    try {
      await fs.promises.rename(tmpPath, dbPath);
    } catch {
      // Rename over a locked file can fail on Windows — fall back to in-place
      await fs.promises.writeFile(dbPath, buffer);
      await fs.promises.rm(tmpPath, { force: true });
    }
    logger.data.info('Database saved to disk');
  } catch (err) {
    logger.data.warn(`Database save failed: ${err}`);
  } finally {
    saveInFlight = false;
    if (saveQueued) {
      saveQueued = false;
      void writeDbToDisk();
    }
  }
}

export function saveDb(): void {
  if (!sqlite || !dbPath) return;
  if (saveTimer) clearTimeout(saveTimer);
  saveTimer = setTimeout(() => {
    saveTimer = null;
    void writeDbToDisk();
  }, SAVE_COALESCE_MS);
}

/** Synchronous final write for shutdown, after which deferred saves are moot. */
function flushDbSync(): void {
  if (saveTimer) {
    clearTimeout(saveTimer);
    saveTimer = null;
  }
  const buffer = exportDbBuffer();
  if (!buffer) return;
  const dir = path.dirname(dbPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  fs.writeFileSync(dbPath, buffer);
  logger.data.info('Database saved to disk');
}

export function closeDb(): void {
  if (sqlite) {
    flushDbSync();
    sqlite.close();
    sqlite = null;
    db = null;
  }
}

export * from './schema';
