import { app } from 'electron';
import { type SQLJsDatabase as DrizzleDatabase, drizzle } from 'drizzle-orm/sql-js';
import { migrate } from 'drizzle-orm/sql-js/migrator';
import * as fs from 'fs';
import * as path from 'path';
import logger from '@/lib/utils/logger';
import * as schema from './schema';

// Dynamic require for sql.js to avoid bundling issues
// eslint-disable-next-line @typescript-eslint/no-require-imports
const initSqlJs = require('sql.js') as typeof import('sql.js').default;
type SqlJsDatabase = import('sql.js').Database;

let db: DrizzleDatabase<typeof schema> | null = null;
let sqlite: SqlJsDatabase | null = null;
let dbPath: string = '';
let migrationsFolder: string = '';

export function getDbPath(): string {
  return path.join(app.getPath('userData'), 'xplane-data.db');
}

/**
 * Read the current schema fingerprint from Drizzle's snapshot.
 * This ID is generated by `drizzle-kit generate` and changes whenever the schema changes.
 */
function getSchemaFingerprint(): string {
  const snapshotDir = path.join(migrationsFolder, 'meta');
  const files = fs
    .readdirSync(snapshotDir)
    .filter((f) => f.endsWith('_snapshot.json'))
    .sort();
  if (files.length === 0) throw new Error('No migration snapshots found in ' + snapshotDir);
  const latestFile = files[files.length - 1]!;
  const snapshot = JSON.parse(fs.readFileSync(path.join(snapshotDir, latestFile), 'utf-8'));
  if (!snapshot.id) throw new Error('Migration snapshot missing id field');
  return snapshot.id;
}

/**
 * Clean up leftover .old-* database files from previous failed deletions (Windows file lock workaround).
 */
function cleanupOldDbFiles(): void {
  try {
    const dir = path.dirname(dbPath);
    const base = path.basename(dbPath);
    for (const file of fs.readdirSync(dir)) {
      if (file.startsWith(base + '.old-')) {
        try {
          fs.unlinkSync(path.join(dir, file));
        } catch {
          /* still locked, will retry next launch */
        }
      }
    }
  } catch {
    /* non-critical */
  }
}

/**
 * Delete the database if its schema doesn't match the current Drizzle snapshot.
 * The DB is purely a cache of X-Plane files — all data is rescanned automatically.
 */
function deleteStaleDb(fingerprint: string): void {
  if (!fs.existsSync(dbPath)) return;

  const versionPath = dbPath + '.version';
  let stored = '';

  try {
    stored = fs.existsSync(versionPath) ? fs.readFileSync(versionPath, 'utf-8').trim() : '';
  } catch {
    stored = '';
  }

  if (stored !== fingerprint) {
    logger.data.info(`Schema changed — deleting stale database`);
    try {
      fs.unlinkSync(dbPath);
    } catch {
      // Windows: file may be locked by antivirus/indexer — rename as fallback
      fs.renameSync(dbPath, `${dbPath}.old-${Date.now()}`);
    }
    try {
      fs.unlinkSync(versionPath);
    } catch {
      /* already gone */
    }
  }
}

export async function initDb(): Promise<DrizzleDatabase<typeof schema>> {
  if (db) return db;

  dbPath = getDbPath();
  migrationsFolder = path.join(app.getAppPath(), 'drizzle');

  logger.data.info(`Database initializing: ${dbPath}`);

  cleanupOldDbFiles();

  const fingerprint = getSchemaFingerprint();
  deleteStaleDb(fingerprint);

  const SQL = await initSqlJs();

  let data: Buffer | undefined;
  if (fs.existsSync(dbPath)) {
    data = fs.readFileSync(dbPath);
  }

  try {
    sqlite = new SQL.Database(data);
    db = drizzle(sqlite, { schema });
    migrate(db, { migrationsFolder });
  } catch (err) {
    sqlite = null;
    db = null;
    throw err;
  }

  fs.writeFileSync(dbPath + '.version', fingerprint);

  logger.data.info(`Database initialized: ${dbPath}`);
  return db;
}

export function getDb(): DrizzleDatabase<typeof schema> {
  if (!db) {
    throw new Error('Database not initialized. Call initDb() first.');
  }
  return db;
}

export function saveDb(): void {
  if (!sqlite || !dbPath) return;

  const data = sqlite.export();
  const buffer = Buffer.from(data);

  const dir = path.dirname(dbPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  fs.writeFileSync(dbPath, buffer);
  logger.data.info('Database saved to disk');
}

export function closeDb(): void {
  if (sqlite) {
    saveDb();
    sqlite.close();
    sqlite = null;
    db = null;
  }
}

export * from './schema';
