[changelog]
header = "# Changelog\n\nAll notable changes to this project will be documented in this file.\n"
body = """
{% if version %}## {{ version }} - {{ timestamp | date(format="%Y-%m-%d") }}{% else %}## Unreleased{% endif %}
{% for group, commits in commits | unique(attribute="message") | filter(attribute="merge_commit", value=false) | group_by(attribute="group") %}
### {{ group | striptags | trim | upper_first }}
{% for commit in commits %}
- {% if commit.scope %}**{{ commit.scope }}:** {% endif %}{% if commit.breaking %}[**breaking**] {% endif %}\
{{ commit.message | upper_first }}\
{% if commit.remote.username %} by @{{ commit.remote.username }}{%- endif %}\
{% if commit.remote.pr_number %} in [#{{ commit.remote.pr_number }}](https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/pull/{{ commit.remote.pr_number }}){%- endif %}\
 ([{{ commit.id | truncate(length=7, end="") }}](https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/commit/{{ commit.id }}))\
{% endfor %}
{% endfor %}

{% if github.contributors | filter(attribute="is_first_time", value=true) | length > 0 %}
### New Contributors
{% for contributor in github.contributors | filter(attribute="is_first_time", value=true) %}
- @{{ contributor.username }} made their first contribution\
{% if contributor.pr_number %} in [#{{ contributor.pr_number }}](https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/pull/{{ contributor.pr_number }}){%- endif %}
{%- endfor %}
{% endif %}
"""
footer = "<!-- generated by git-cliff -->"
trim = true

[remote.github]
owner = "lyestarzalt"
repo = "x-dispatch"

[git]
conventional_commits = true
filter_unconventional = true
protect_breaking_commits = true
filter_commits = false
tag_pattern = "v[0-9].*"
sort_commits = "oldest"
commit_parsers = [
  { message = "^feat", group = "<!-- 0 -->Features" },
  { message = "^fix", group = "<!-- 1 -->Bug Fixes" },
  { message = "^perf", group = "<!-- 2 -->Performance" },
  { message = "^refactor", group = "<!-- 3 -->Refactor" },
  { message = "^docs", group = "<!-- 4 -->Documentation" },
  { message = "^style", group = "<!-- 5 -->Styling" },
  { message = "^chore", group = "<!-- 6 -->Miscellaneous" },
  { message = "^ci", group = "<!-- 7 -->CI/CD" },
  { message = "^release", group = "<!-- 8 -->Release" },
]
link_parsers = [
  { pattern = "#(\\d+)", href = "https://github.com/lyestarzalt/x-dispatch/issues/$1" },
]
