import type maplibregl from 'maplibre-gl';

/**
 * Map style transition logic, extracted so it can be unit-tested without
 * pulling in the rest of `globeUtils.ts` (which imports `maplibre-contour`,
 * `@geoql/maplibre-gl-starfield`, and other deps that don't transform
 * cleanly under Vitest).
 */

// Per-map snapshot of the *current* basemap's source/layer IDs (i.e. what
// MapLibre loaded from the style URL, before any app-added custom layers).
// preserveCustomStyle reads this on style transitions to distinguish:
//   - leftover layers/sources from the *previous* basemap (drop them — the
//     new basemap's `next.*` replaces them)
//   - app-added custom layers/sources (carry forward into the new style)
// Without it, cross-provider switches (e.g. Carto → OFM) leak the old
// basemap's source + non-overlapping layer IDs into the new style, leaving
// both basemaps stacked and the theme half-applied.
type BasemapSnapshot = { sources: Set<string>; layers: Set<string> };
const basemapSnapshots = new WeakMap<maplibregl.Map, BasemapSnapshot>();

// Known basemap-vendor source IDs. We *never* carry these across style
// transitions, regardless of whether the snapshot has them — this is the
// belt-and-suspenders pass that protects against state corrupted by older
// builds that didn't snapshot, and against future basemap providers that
// share an ID across styles. Layers referencing one of these sources are
// also dropped.
const KNOWN_BASEMAP_SOURCE_IDS: ReadonlySet<string> = new Set([
  'openmaptiles', // OpenFreeMap, MapTiler, Stadia
  'carto', // CARTO Positron / Dark Matter / Voyager
  'ne2_shaded', // OpenFreeMap natural-earth raster underlay
  'composite', // Mapbox Streets & friends
  'planet', // Various OSM-derived styles
  'raster', // Generated by tileUrlToStyle for raster-tile URLs (Esri, OSM, etc.)
]);

function snapshotOf(style: maplibregl.StyleSpecification): BasemapSnapshot {
  return {
    sources: new Set(Object.keys(style.sources ?? {})),
    layers: new Set((style.layers ?? []).map((l) => l.id)),
  };
}

export function captureBasemapSnapshot(map: maplibregl.Map): void {
  basemapSnapshots.set(map, snapshotOf(map.getStyle()));
}

/**
 * Build a transformStyle callback bound to a specific map instance. The
 * callback distinguishes app-added custom layers/sources (which it carries
 * forward) from leftovers of the previous basemap (which it drops).
 *
 * State lives in `basemapSnapshots` (keyed by the map instance), populated
 * initially by `captureBasemapSnapshot` on map 'load' and refreshed here
 * after every transition.
 *
 * @param terrainShadingLayerIds layer IDs that should be inserted before
 *   the first symbol layer of the new basemap (so they render below labels)
 * @param starfieldLayerId layer ID of the starfield (rendered before all
 *   other layers, including the basemap)
 */
export function makePreserveCustomStyle(
  map: maplibregl.Map,
  terrainShadingLayerIds: ReadonlyArray<string>,
  starfieldLayerId: string
) {
  return function preserveCustomStyle(
    previous: maplibregl.StyleSpecification | undefined,
    next: maplibregl.StyleSpecification
  ): maplibregl.StyleSpecification {
    if (!previous) {
      basemapSnapshots.set(map, snapshotOf(next));
      return next;
    }

    // Fall back to assuming the entire previous style was the basemap if no
    // snapshot was captured yet — preserves old behaviour for safety.
    const previousBasemap = basemapSnapshots.get(map) ?? snapshotOf(previous);

    const customSources: Record<string, maplibregl.SourceSpecification> = {};
    for (const [id, source] of Object.entries(previous.sources ?? {})) {
      if (previousBasemap.sources.has(id)) continue;
      if (KNOWN_BASEMAP_SOURCE_IDS.has(id)) continue;
      customSources[id] = source as maplibregl.SourceSpecification;
    }

    const customLayers = (previous.layers ?? []).filter((l) => {
      if (previousBasemap.layers.has(l.id)) return false;
      const src = (l as { source?: string }).source;
      if (src && KNOWN_BASEMAP_SOURCE_IDS.has(src)) return false;
      // The `background` layer type is always a basemap concept (the
      // bottommost flat fill that fills space where no tiles render).
      // Vendor styles all define one; the app never adds its own. Dropping
      // by type rather than ID protects against the layer being named
      // something other than 'background' in a future style.
      if (l.type === 'background') return false;
      return true;
    });

    // Snapshot the new basemap's IDs so the *next* transition knows what to drop.
    basemapSnapshots.set(map, snapshotOf(next));

    // Insert terrain shading layers (hillshade, contours) before the first
    // symbol layer so they render below labels; everything else goes on top.
    const terrainIds = new Set(terrainShadingLayerIds);
    const starfieldLayer = customLayers.filter((l) => l.id === starfieldLayerId);
    const terrainLayers = customLayers.filter((l) => terrainIds.has(l.id));
    const otherLayers = customLayers.filter(
      (l) => !terrainIds.has(l.id) && l.id !== starfieldLayerId
    );

    // Starfield goes first (behind everything)
    const layers = [...starfieldLayer, ...next.layers];
    if (terrainLayers.length > 0) {
      const symbolIdx = layers.findIndex((l) => l.type === 'symbol');
      if (symbolIdx >= 0) {
        layers.splice(symbolIdx, 0, ...terrainLayers);
      } else {
        layers.push(...terrainLayers);
      }
    }
    layers.push(...otherLayers);

    // Defensive dedup: if any layer ID slipped through (e.g. corrupted previous
    // state, edge cases the snapshot/blacklist don't catch), keep only the
    // first occurrence. MapLibre's `setStyle` rejects styles with duplicate
    // layer IDs (`layers[N]: duplicate layer id "X"`), which crashes the
    // entire transition and leaves the map blank. The order is
    // `[starfield, ...next.layers, ...terrain, ...other]`, so the basemap
    // (next) takes priority over leftover customs with the same ID.
    const seenLayers = new Set<string>();
    const dedupedLayers = layers.filter((l) => {
      if (seenLayers.has(l.id)) return false;
      seenLayers.add(l.id);
      return true;
    });

    return {
      ...next,
      sources: { ...next.sources, ...customSources },
      layers: dedupedLayers,
      terrain: previous.terrain ?? next.terrain,
      sky: previous.sky ?? next.sky,
    };
  };
}
